User tag index api
NAKKA-K/musclers pull request #178
Opened 2019-11-19 05:39 UTC by yokotakento

connect to #

# 概要

# 変更点

- 変更内容
- 変更内容

# スクリーンショット

# 関連issue

- [ ] あればissue番号を
#175

# 留意事項・参考

留意事項や参考があれば

2019-11-19 05:46 UTC, kageyasai2 commented on backend/app/controllers/api/tags_controller.rb
> +        }
実はここのJsonは自分で書かなくても `success_res()とerror_res()`  っていう自作関数が用意されてるから使うといいよ
たしか `application_controller.rb` に宣言されてたはず
あとcurrent_userの値が `null` の場合の処理ｍ書いた方がいいかも
nullの場合 'error_res()' を用いてエラーメッセージを設定してjsonを返したりね

2019-11-19 05:48 UTC, yokotakento commented on backend/app/controllers/api/tags_controller.rb
> +        }
わかりました、調べて直します。

2019-11-19 05:50 UTC, NAKKA-K commented on backend/app/controllers/api/tags_controller.rb
> +        }
current_userがnullの場合は401

2019-11-20 04:26 UTC, NAKKA-K commented on backend/app/controllers/api/tags_controller.rb
> +        if current_user.nil?
これは上のand returnのせいで絶対実行されないコードになってしまってるね。
こっちを先に書かないといけないかな。

2019-11-20 04:26 UTC, kageyasai2 commented on backend/app/controllers/api/tags_controller.rb
> +    end
null判定を処理の最初に持ってこないとsuccess_res()が先に呼ばれてしまうから良くない
ユーザ自身がタグを所有していなくて@user_tagが空の可能性があるから空の場合の処理も追記しといた方がいいかもしれん
空の場合は404エラーを返すとか

2019-11-20 04:32 UTC, kageyasai2 commented
tags_controllerのindex method方もsuccess_res()使うように置き換えといて欲しい

2019-11-20 04:53 UTC, yokotakento commented
すいませんindexメソッドのjson部分直してませんでした。

2019-11-20 05:20 UTC, NAKKA-K approved these changes

2019-11-20 05:21 UTC, NAKKA-K commented
そういえばこの作業のIssueと連携しておいてー

2019-11-20 05:22 UTC, kageyasai2 commented on backend/app/controllers/api/tags_controller.rb
> +        end
```
@user_tags = current_user.user_tags
if @user_tags.blank?
 //エラー処理
else
  //正常の処理
end
```
先に変数に値入れてから判定した方がいいよ
`@user_tags.nil?`より`@user_tags.blank?`の方がnilと空配列の判定を同時にできていいかもしれん

2019-11-20 05:26 UTC, yokotakento commented on backend/app/controllers/api/tags_controller.rb
> +        end
わかりました。直してからまた上げます。

2019-11-20 05:36 UTC, NAKKA-K commented on backend/app/controllers/api/tags_controller.rb
> +        end
今気づいたんだけど、ユーザータグが空だったとしてサービス的には正常動作だから普通に200で返してもいい気がする。
nilだったら`[]`配列にしてほしいけど。

2019-11-20 05:37 UTC, NAKKA-K requested changes
@yokotakento 今気づいたんだけど、ユーザータグが空だったとしてサービス的には正常動作だから普通に200で返してもいい気がする。
nilだったら`[]`配列にしてほしいけど。

2019-11-21 02:35 UTC, kageyasai2 approved these changes

2019-11-21 03:15 UTC, NAKKA-K approved these changes

2019-11-21 03:16 UTC, merged