Blog create api
NAKKA-K/musclers pull request #274
Opened 2019-12-09 02:24 UTC by yokotakento

close #

# 概要

# 変更点

- 変更内容
- 変更内容

# スクリーンショット

# 関連issue

- [x] あればissue番号を
#260 

# 留意事項・参考

留意事項や参考があれば

2019-12-09 02:25 UTC, yokotakento commented
コントローラまでですが、一旦コード見て欲しいです。
よろしくお願いします。

2019-12-09 02:38 UTC, kageyasai2 commented on backend/app/controllers/api/blogs_controller.rb
> +            success_res(
`save!` にしないと例外が帰ってこな買った気がする
`save`だと`true or false` が帰る

2019-12-09 02:39 UTC, kageyasai2 commented on backend/app/controllers/api/blogs_controller.rb
> +                ) and return
インデントをlogger.errorに合わしてほしい

2019-12-09 02:40 UTC, kageyasai2 commented on docs/blueprints/api_blueprint.md
> ++ Request (application/json)
ブログ新規作成のURLが抜けてる

2019-12-09 02:47 UTC, NAKKA-K commented on backend/app/controllers/api/blogs_controller.rb
> +            @blog.save
newとsaveは合わせてcreateを使った方がスッキリするよ

2019-12-09 02:47 UTC, NAKKA-K commented on backend/app/controllers/api/blogs_controller.rb
> +            #何かしらのエラー
何かしらのエラーという括りでエラーハンドリングするのは一番やっちゃいけないから出来ればもっと分割しよう。
エラー原因の特定が大変になったり、不本意なエラーが出た時も気付かなかったり、ユーザーに対してのレスポンスが意味不明になったりするから。

2019-12-09 02:55 UTC, yokotakento commented on backend/app/controllers/api/blogs_controller.rb
> +            #何かしらのエラー
テーブル作成時に特に設けていなかったので、取り敢えずNULL制約と
他に文字数制約とか必要でしょうか？ブログで制約あるのも何かあれですけど

2019-12-09 03:02 UTC, NAKKA-K commented on backend/app/controllers/api/blogs_controller.rb
> +            #何かしらのエラー
取り敢えず空白、空文字は弾いておこう。
何文字以上とかはあってもいいけど、今はなくていいかな。

2019-12-09 03:02 UTC, yokotakento commented on backend/app/controllers/api/blogs_controller.rb
> +            @blog.save
普通に尻に足せばいいですか？
![image](https://user-images.githubusercontent.com/45554815/70403917-a503a300-1a7b-11ea-9b8e-facff9ca14b1.png)

2019-12-09 03:06 UTC, NAKKA-K commented on backend/app/controllers/api/blogs_controller.rb
> +            @blog.save
Blog.create!

2019-12-09 04:21 UTC, yokotakento commented on backend/app/controllers/api/blogs_controller.rb
> +            #何かしらのエラー
マイグレーションの方のNOT NULL制約のデフォルト値はどうしましょう？
Nicknameみたく `default: ""` でいいんですかね？

2019-12-09 04:34 UTC, kageyasai2 commented on backend/app/controllers/api/blogs_controller.rb
> +            #何かしらのエラー
いいよ

2019-12-09 05:27 UTC, yokotakento commented
コメント貰ったところ修正しました。またレビュー願いしたいです。

2019-12-09 05:32 UTC, NAKKA-K reviewed
migrationファイルを変更した場合はrails db:migrateを走らせてからschema.rbも一緒にコミットしてほしい

2019-12-09 05:42 UTC, yokotakento commented
ありがとうございます、マイグレーションしました。以後気をつけます・・・

2019-12-09 05:44 UTC, NAKKA-K approved these changes
良さげ

2019-12-09 05:45 UTC, NAKKA-K requested changes

2019-12-09 05:45 UTC, NAKKA-K commented on docs/blueprints/api_blueprint.md
> +
そういえば422のエラーレスポンス書いてないな

2019-12-11 04:42 UTC, yokotakento commented
普通に例のごとくRSpecでエラー吐かれてて、1つ目のエラーは
titleとbodyが空のブログをテストデータで渡せばいいと思うんですけど、
それがよく分かっていなくて・・・あと、二つ目は謎のブログ詳細のmessageが出てます。
![image](https://user-images.githubusercontent.com/45554815/70592134-0e221c80-1c1c-11ea-9fc9-0dda8e8e5484.png)

2019-12-11 04:44 UTC, kageyasai2 commented on backend/spec/requests/blog_api_spec.rb
> +        end
多分新規作成の場合getじゃなくてpostじゃない？

2019-12-11 04:45 UTC, kageyasai2 commented on backend/spec/requests/blog_api_spec.rb
> +        end
`docker exec api_rails rails routes`  で `blogs#create` に対応するリクエストメソッドを確認できる

2019-12-11 04:49 UTC, kageyasai2 commented on backend/spec/requests/blog_api_spec.rb
> +        end
新規作成APIの場合は65から67行目で作成してるブログIDとかは必要ないと思う

2019-12-11 05:00 UTC, yokotakento commented on backend/spec/requests/blog_api_spec.rb
> +        end
showメソッドが呼び出されている・・・？
![image](https://user-images.githubusercontent.com/45554815/70592900-91447200-1c1e-11ea-8eae-dfb232b3459f.png)

2019-12-11 05:01 UTC, NAKKA-K commented on backend/spec/requests/blog_api_spec.rb
> +        end
そうだね

2019-12-11 05:09 UTC, kageyasai2 commented on backend/spec/requests/blog_api_spec.rb
> +        end
多分pathが違う
`rails routes` を実行した時に一番左に出力されるprefixのところと照らし合わせればわかるはず

2019-12-11 05:11 UTC, NAKKA-K commented on backend/spec/requests/blog_api_spec.rb
> +        end
メソッド, パス, 引数が違うかな

2019-12-11 05:19 UTC, yokotakento commented on backend/spec/requests/blog_api_spec.rb
> +        end
普通に間違ってました。ありがとうございます。
そのあと実行したら401吐かれたんで、postの後ろにheaders: @headers付けたら500になりました・・・
![image](https://user-images.githubusercontent.com/45554815/70593634-25afd400-1c21-11ea-9002-62b2dbf98dcc.png)

2019-12-11 05:20 UTC, NAKKA-K commented on backend/spec/requests/blog_api_spec.rb
> +        end
ちゃんとしたAPIに接続できた結果、次はコントローラーの実装でバグが発生したのかな。
進んだ

2019-12-11 05:41 UTC, yokotakento commented on backend/spec/requests/blog_api_spec.rb
> +        end
え、500ってことはネットワークかデータベースのエラーですよね？

2019-12-11 05:42 UTC, NAKKA-K commented on backend/spec/requests/blog_api_spec.rb
> +        end
いや、サーバー側で例外が発生すれば500番。

2019-12-11 05:43 UTC, NAKKA-K commented on backend/app/controllers/api/blogs_controller.rb
> +            error_res(
というか自分で500番返してるじゃん

2019-12-11 05:50 UTC, yokotakento commented on backend/app/controllers/api/blogs_controller.rb
> +            error_res(
いやまあそうなんですけど、つまりコントローラでcreateメソッドがうまくできてないってことですよね？

2019-12-11 05:51 UTC, NAKKA-K commented on backend/app/controllers/api/blogs_controller.rb
> +            error_res(
そうだね。
モデルのバリデーションなり、DBの制約なり、配列のmergeなり、begin句での例外発生。

2019-12-11 13:46 UTC, kageyasai2 commented on backend/app/controllers/api/blogs_controller.rb
> +            error_res(
エラーを出力してみるといいかも

2019-12-12 04:53 UTC, yokotakento commented
なんかもうお手上げ状態なので、助けてください。

2019-12-12 05:16 UTC, kageyasai2 commented
どこで積んでる？

2019-12-12 05:36 UTC, yokotakento commented
色々あるんですけど、大本がブログの値を受け取る`params.require(:blog).permit(:title, body)`でのrequire、こいつが想定したオブジェクトとして値が受け取れていないのが問題だと思います・・・requireを外すと受け取れますがblogオブジェクトとして受け取れていない時点でtitleとbodyが無いので200時に422が返るエラーが出ます。

2019-12-12 05:39 UTC, NAKKA-K commented
titleとbodyが送られてこないとpermitでParamsErrorになるから、一回受け取りたいならpermitも書かなければいい。
もしくはfetchとかを使ってなかった場合のデフォルト値を指定してやるとか。

2019-12-12 05:49 UTC, yokotakento commented
paramsをすっ飛ばしたら、200と422の両方で500が返ってきます。

2019-12-12 05:50 UTC, NAKKA-K commented
paramsをなくすなら自分でnullチェックとかをして制御してね

2019-12-13 01:11 UTC, kageyasai2 commented on backend/spec/requests/blog_api_spec.rb
> +        end
このpathてどのAPIなんだろ
ブログAPI(今回の場合ブログ作成APIか)でログインできないかどうか確かめないと意味ないぜよ

2019-12-20 08:32 UTC, NAKKA-K commented
分かりそう？
もっと質問してね

2020-01-10 01:55 UTC, NAKKA-K commented
分かりそう？
もっと質問してね

2020-01-24 05:17 UTC, NAKKA-K commented
最近Musclersのコード読んでなさすぎて感覚忘れてた。
多分雰囲気あってそう。
これって完成？

2020-01-24 05:46 UTC, yokotakento commented
自分で見た感じはエラー出なかったので一応完成（？）のつもりです・・・

2020-01-27 03:02 UTC, NAKKA-K approved these changes
テストが通るならOK！

approve忘れてた......ごめんなさい！

2020-01-27 03:04 UTC, merged