Register api
NAKKA-K/musclers pull request #66
Opened 2019-10-03 07:19 UTC by kageyasai2

やったこと
・フロントエンドとバックエンドでのバリデーションチェック
・新規登録画面からEメールを入力してユーザデータの更新ができるようになった
・APIドキュメントの更新

できてないこと
 Facebook認証をした後にEメールが入力されていなければ新規登録の画面に遷移してほしいのだがしてくれない。
金曜日のレビューまでには問題を解決したい

`index.vue` に新規登録へのリンクを追加しており、新規登録の動作確認は一応できる

2019-10-03 08:12 UTC, NAKKA-K commented on frontend/pages/register.vue
> +    emailErrors() {
text inputにはtype=emailがあると思うけどvuetifyにはない？
もしあればvalidationを実装しなくてもいいような気がするけど

2019-10-03 08:12 UTC, NAKKA-K commented on backend/app/controllers/api/users_controller.rb
> +        error_res(500, message: '更新に失敗しました',err: '更新に失敗しました') and return
これだとエラーを握りつぶしてるからloggerなりなんなりにエラーを表示した方がいい。

2019-10-03 08:12 UTC, NAKKA-K commented on backend/app/models/user.rb
> +  validates :email, uniqueness: true, allow_blank: true, format: { with: VALID_EMAIL_REGEX }
`validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } `
こういうvalidatorもあるよ。
どっちがよかったのかは覚えてないけど

2019-10-03 08:12 UTC, NAKKA-K commented on docs/api_blueprint.md
> +## Users [/api/users/{user_id}]
230行目に書くのが正しいかな。
同じルーティングだから。

2019-10-03 08:12 UTC, NAKKA-K commented on docs/api_blueprint.md
> +    + email: huga@hoge.com (string) - ユーザのEメール
これはparametersじゃなくてRequestじゃないかな。
書く場所としては`### ユーザ情報更新 [PATCH]`の下かな。

2019-10-03 08:12 UTC, NAKKA-K commented on docs/api_blueprint.md
> +    + email: huga@hoge.com (string) - ユーザのEメール
Headersも書いた方がいいかな。
認証が必須だからね。

2019-10-03 08:12 UTC, NAKKA-K commented on backend/app/controllers/api/users_controller.rb
> +        error_res(422, message: 'バリデーションエラー',err: e.record.errors) and return
バリデーションエラーだとユーザーは何のことか分からないから、'入力が正しくありません'とか'内容を再度ご確認ください'とかそういう感じにした方がいいかも。

2019-10-03 08:12 UTC, NAKKA-K commented on frontend/package.json
> +    "vuelidate": "^0.7.4",
vuelidateの決定理由とかって特別あったりする？
(ちょっと気になっただけ)

2019-10-03 08:12 UTC, NAKKA-K commented on backend/app/models/user.rb
> +  validates :email, uniqueness: true, allow_blank: true, format: { with: VALID_EMAIL_REGEX }
validatesの空設定こういう感じにしたのか。
いいね

2019-10-03 08:13 UTC, NAKKA-K commented on frontend/pages/callback.vue
> +        this.$router.push('/register') // TODO: Email等の入力画面に遷移させる
プルリクにregister画面に遷移できないって書いてあったけど、このifには入ってる？

2019-10-03 08:41 UTC, kageyasai2 commented on frontend/package.json
> +    "vuelidate": "^0.7.4",
Vuetify公式にもvuelidateを用いたサンプルがあったし、導入が簡単で扱いやすそうだったからかな
エラーメッセージも簡単に表示できるし結構良さげと思う

2019-10-03 08:41 UTC, kageyasai2 commented on docs/api_blueprint.md
> +    + email: huga@hoge.com (string) - ユーザのEメール
修正します

2019-10-03 08:41 UTC, kageyasai2 commented on backend/app/models/user.rb
> +  validates :email, uniqueness: true, allow_blank: true, format: { with: VALID_EMAIL_REGEX }
`validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }`
rubyの標準ライブラリにあるなら使用したほうがいいね

2019-10-03 08:41 UTC, kageyasai2 commented on frontend/pages/register.vue
> +    emailErrors() {
Vuetifyの公式確認してみたけど無さそう
validationに関しては現段階だとEメールの項目しか無いけど将来的に入力項目を増やすことを考えたら実装しといた方がいいと思った

2019-10-03 08:41 UTC, kageyasai2 commented on frontend/pages/callback.vue
> +        this.$router.push('/register') // TODO: Email等の入力画面に遷移させる
入ってない

2019-10-03 09:36 UTC, kageyasai2 commented
@NAKKA-K 新規登録に遷移できない問題以外の指摘内容修正したから確認お願い

2019-10-03 09:40 UTC, NAKKA-K commented
おっけい

2019-10-03 09:48 UTC, NAKKA-K commented on frontend/pages/callback.vue
> +        this.$router.push('/register') // TODO: Email等の入力画面に遷移させる
何が原因か全く分からないけど条件分は少しでも綺麗にした方が楽だろうから、ifとelseを逆にする方がいいかも……？？

2019-10-03 09:51 UTC, NAKKA-K commented on frontend/pages/callback.vue
> +        this.$router.push('/register') // TODO: Email等の入力画面に遷移させる
後は、emailは本当に空になってるか調べてみるくらいしか分からん

2019-10-03 12:50 UTC, kageyasai2 commented on frontend/pages/callback.vue
> +        this.$router.push('/register') // TODO: Email等の入力画面に遷移させる
`const res = await this.$axios.$post('/api/auth/sign_in', postData)` 21行目までは実行されてるみたい
catchの方に飛んでるのかと思ったけどエラーログ何も吐かれてないしお手上げ状態

2019-10-07 04:19 UTC, various3211workd commented
解決したんやね。
おめ

2019-10-07 04:19 UTC, various3211workd approved these changes

2019-10-07 04:20 UTC, NAKKA-K commented on frontend/pages/redirect.vue
> +          this.$router.push('/users')
ここのURLが間違ってるかも。
おそらくhome.vueとかに飛ばすのが正しいのかな。

2019-10-07 04:20 UTC, NAKKA-K commented on frontend/pages/redirect.vue
> +        console.error(err)
sign_inできなかった場合の処理を書いてないと怖いね。
loginページにリダイレクトでいいのかな？

2019-10-07 04:20 UTC, Raccoo approved these changes

2019-10-07 04:21 UTC, NAKKA-K requested changes
要修正レビューあり。

こんなのあったの気づかなかった

2019-10-07 04:23 UTC, kageyasai2 commented on frontend/pages/redirect.vue
> +        console.error(err)
loginページで良さそう

2019-10-07 04:23 UTC, kageyasai2 commented on frontend/pages/redirect.vue
> +          this.$router.push('/users')
home.vue無いんだけどindex.vueでいいかな

2019-10-07 04:24 UTC, NAKKA-K commented on frontend/pages/redirect.vue
> +          this.$router.push('/users')
外枠だけでもページを作ってやった方がいいかな

2019-10-07 04:24 UTC, NAKKA-K commented on frontend/pages/redirect.vue
> +        console.error(err)
👍

2019-10-07 04:24 UTC, kageyasai2 commented on frontend/pages/redirect.vue
> +          this.$router.push('/users')
OK

2019-10-07 04:35 UTC, kageyasai2 commented
修正しました

2019-10-07 04:49 UTC, NAKKA-K approved these changes
LGTM!

2019-10-07 04:50 UTC, merged